"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from os import path
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^=6-_k)oh!n9-fpcd1qd0rf(!8y2!!8cc*so1if(!*ydv@*_dc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
]

SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.import_export',
    'unfold.contrib.filters',
    "unfold.contrib.forms",
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'masjidku',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            path.normpath(path.join(BASE_DIR, "masjidku/templates")),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "masjidku.context_processors.get_settings",
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mysite.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT =  BASE_DIR / 'static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRISPY_TEMPLATE_PACK = "unfold_crispy"
CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]

UNFOLD = { 
    "SITE_TITLE": _("MasjidKu"),
    "SITE_HEADER": _("MasjidKu"),
    "SITE_SUBHEADER": _("MasdjidKu Administration"),

    "DASHBOARD_CALLBACK": "masjidku.views.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _(""),
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Master Data"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Buku Kas"),
                        "icon": "wallet",
                        "link": reverse_lazy("admin:masjidku_buku_changelist"),
                        "permission": lambda request: request.user.has_perm("masjidku.view_buku"),
                    },
                    {
                        "title": _("Kategori Transaksi"),
                        "icon": "category",
                        "link": reverse_lazy("admin:masjidku_kategoritransaksi_changelist"),
                        "permission": lambda request: request.user.has_perm("masjidku.view_kategoritransaksi"),
                    },
                    {
                        "title": _("Jamaah"),
                        "icon": "group",
                        "link": reverse_lazy("admin:masjidku_jamaah_changelist"),
                        "permission": lambda request: request.user.has_perm("masjidku.view_jamaah"),
                    },
                ],
            },
            {
                "title": _("Pengaturan Web"),
                "items": [
                    {
                        "title": _("Halaman"),
                        "icon": "article",
                        "link": reverse_lazy("admin:masjidku_page_changelist"),
                    },
                    {
                        "title": _("Foto Galeri"),
                        "icon": "image",
                        "link": reverse_lazy("admin:masjidku_galeri_changelist"),
                    },
                    {
                        "title": _("Laporan"),
                        "icon": "dataset",
                        "link": reverse_lazy("admin:masjidku_laporan_changelist"),
                    },
                ],
            },
            {
                "title": _("Pencatatan Keuangan"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Pemasukan"),
                        "icon": "attach_money",
                        "link": reverse_lazy("admin:masjidku_transaksipemasukan_changelist"),
                        "permission": lambda request: request.user.has_perm("masjidku.view_transaksipemasukan"),
                    },
                    {
                        "title": _("Pengeluaran"),
                        "icon": "shopping_cart_checkout",
                        "link": reverse_lazy("admin:masjidku_transaksipengeluaran_changelist"),
                        "permission": lambda request: request.user.has_perm("masjidku.view_transaksipengeluaran")
                    },
                    {
                        "title": _("Konfirmasi Donasi"),
                        "icon": "verified",
                        "link": reverse_lazy("admin:masjidku_donasi_changelist"),
                        "permission": lambda request: request.user.has_perm("masjidku.view_donasi")
                    },
                    {
                        "title": _("Saldo Mingguan"),
                        "icon": "attach_money",
                        "link": reverse_lazy("admin:masjidku_saldomingguan_changelist"),
                        "permission": lambda request: request.user.has_perm("masjidku.view_saldomingguan")
                    },
                    {
                        "title": _("Saldo Bulanan"),
                        "icon": "attach_money",
                        "link": reverse_lazy("admin:masjidku_saldobulan_changelist"),
                        "permission": lambda request: request.user.has_perm("masjidku.view_saldobulan")
                    },
                ],
            },
            {
                "title": _("Users & Groups"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.has_perm("masjidku.view_user")
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },

        ],
    },
}
